name: Deploy to AKS

on:
  workflow_run:
    #workflows: ["Build and Push to ACR"]
    #types:
    #  - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ secrets.AKS_RG }}
        cluster-name: ${{ secrets.AKS_NAME }}

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          k8s/deployment.yml
          k8s/service.yml
        images: |
          ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.run_number }}
