name: Build and Push to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: youracrname    
  IMAGE_NAME: demoapp
  AZURE_CREDENTIALS: dummy         

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }} .
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    - name: Logout
      run: az logout

